### ISSUE TITLE
Serialize CLOSXP values

### ISSUE THREAD

**Issue by fghibellini** [PRL-PRG/genthat#3]

**Comment by mvacha** [comment]
### Research
Closure = function (body+parameters) and enclosed environment. Closure could be passed into the function either as an CLOSXP expression or as a LANGSXP.

#### CLOSXP
```
x <- function(a) 1
g(x)
```
#### LANGSXP
```
g(function(a) 1)
```

### Current status:
- LANGSXP serialization fails, because serialization does not support all the subexpr types.
- CLOSXP serialization does not work.

### Tasks:
